image:
  file: .gitpod.Dockerfile

tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest &&
      go install honnef.co/go/tools/cmd/staticcheck@latest &&
      go install golang.org/x/tools/cmd/goimports@latest &&
      go install github.com/go-delve/delve/cmd/dlv@latest &&
      go install golang.org/x/perf/cmd/benchstat@latest &&
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /workspace/try-treesitter/rustup-init.sh &&
      sudo sh /workspace/try-treesitter/rustup-init.sh -y --default-toolchain stable
    command:
      go version


vscode:
  extensions:
    - golang.go
    - TakumiI.markdowntable